config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get 'search' => 'cards#query'

  get 'decks/new'

  resources :cards

end

app/models/bridge.rb
class Bridge < ActiveRecord::Base
	belongs_to :card
	belongs_to :deck
end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :bridges
	has_many :decks, :through => :bridges
	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false }
	# Takes input card record and outputs list of deck records
	def what_decks
		b = Bridge.where(card_id:self.id)
		deck_ids = []
		b.each do |bridge|
			deck_ids.push(bridge.deck_id)
		end
		deck_list = []
		deck_ids.each do |id|
			deck_list.push(Deck.find(id))
		end
		return deck_list
	end

end

app/models/deck.rb
class Deck < ActiveRecord::Base
	has_many :bridges
	has_many :decks, :through => :bridges

	def getCards
		list = Bridge.where(deck_id:self.id)
		names = []
		list.each do |bridge|

			card = Card.find(bridge.card_id)
			if bridge.duplicate
				card.name = card.name + ' x2'
			end
			names.push(card.name)
		end
		return names
	end

	def has? card_record
		Bridge.exists?(deck_id:self.id,card_id:card_record.id)
	end
end

app/models/example_users.rb
class User
	attr_accessor :name, :email, :password, :password_confirmed
	# first line  
	



end

app/models/helloworld.rb
class HelloWorld
   def initialize(name)
      @name = name.capitalize
   end
   def sayHi
      puts "Hello #{@name}!"
   end
end

hello = HelloWorld.new("World")
hello.sayHi

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
  	render :template => "layouts/application"
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	# root page input logic
	def index
		term = params[:term]
		while term =~ /(.*),/
			term.slice!(/(.*),/)
		end
		term.strip!
		term.capitalize!
		puts term
		if term.length > 2
			@cards = Card.order(:name).where("name LIKE ?", "#{term}%")
			render json: @cards.map(&:name)
		end
	end

  def new
  	puts 'hello'
  end

  def show
  	deck = Deck.find(params[:id])

  	@list = deck.getCards
  end

  # search database for matching decks
  def query
		if params[:search]
			criteria = params[:search].split(',')
			criteria.each_with_index do |criterium,i|
				criterium.sub! /,/, ''
				criterium.strip!
				criterium = criterium.split.map(&:capitalize).join(' ')
			end
			criteria.delete_if {|i| i.empty?}
			criteria.each_with_index do |card_name,i|
				c = Card.find_by(name: card_name)	
				if !c
					@decks = 'NO RESULTS'
					return
				end
				if(i == 0) 
					@decks = c.what_decks
				else
					#filter an array of decks by card record c
					@decks.delete_if {|deck| !deck.has?(c)}
				end
			end
		else
			@decks = false
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.erb
<%= image_tag "hearthstone.png", class: "logo" %>
<h1>What Deck are you playing against?</h1>
<!-- list cards in deck -->
 <%= form_tag('/cards/index', :method => "get", class: "deck-search", id: "deck-search") do %>
    <div class="input-container">
      <%= text_field_tag :search, params[:search], class: "add", placeholder: " Add a few cards.." %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i></button>
    </div>
  <% end %>
  <% if @decks %>
		<% @decks.each do |deck| %>
			<p>  <%= deck %> </p>
		<% end %>
	<% else %>
		<p> waiting for input </p>
	<% end %>

app/views/cards/new.html.erb
<h1>What Hearthstone Deck are you playing against</h1>

app/views/cards/query.html.erb
<% content_for :table do %>
  <div class="deck-parent"> 
  <table>
    <thead>
      <tr>
        <th>
          <span>#</span>
        </th>
        <th>
          <span>name</span>
        </th>
      </tr>
    </thead>
    <tbody>
      
      <% if @decks == 'NO RESULTS'%>
        <tr><td> 1 </td><td><%= @decks %> </td></tr>
      <% elsif @decks.is_a? Array %>
        <% @decks.each_with_index do |deck,i| %>
          <tr><td><%="#{i+1}"%></td>
          <td><%= link_to("#{deck.name}", "http://www.hearthhead.com/deck=#{deck.hearthhead_id}", :target => "_blank")%> </td></tr>
        <% end %>
      <% else %>
        <tr><td> 1 </td><td>Empty Query</td></tr>
      <% end %>
    </tbody>
  </table>
  </div>

<% end %>

app/views/cards/show.html.erb
<%= image_tag "hearthstone.png", class: "logo" %>
<h1>What Deck are you playing against?</h1>
<!-- list cards in deck -->
 <%= form_tag(articles_path, :method => "get", class: "deck-search", id: "deck-search") do %>
    <div class="input-container">
      <%= text_field_tag :search, params[:search], class: "add", placeholder: " Add a few cards.." %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i></button>
    </div>
  <% end %>
  <%= yield %>
<% @list.each do |card| %>
	<p>  <%= card %> </p>
<% end %>

app/views/layouts/_before_query.html.erb
<div class="img-container" id="">
	<div class="row">
		<div class ="col-md-4"></div>
		<div class ="col-md-4">
			<%= image_tag "card-backs.png", class: "cards-img" %>
			<p>Find out what decks your opponents are playing</p></div>
		<div class ="col-md-4"></div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="" id="footer">
	<div class="col-md-12">BUILT BY TY CONNORS</div>
</div>

app/views/layouts/_index.html.erb
<%= image_tag "hearthstone.png", class: "logo" %>
<!-- Possible Cards Seen Listing
<div class="seen-list">
  <h3>CARDS SEEN</h3>
  <ul>
    <li><%= @cards %></li>
  </ul>
</div>
-->

<div class ="col-md-5">
  <%= image_tag "aspirations.png", class: "legend-img" %>
</div>
 <%= form_tag('/search', :method => "get", class: "deck-search", id: "deck-search") do %>
    <div class="input-container">
      <label for="search">Card Name(s)</label><br/>
      <%= text_field_tag :search, params[:search], id: "search", class: "add", placeholder: " Add a few cards..", data: {autocomplete_source: cards_path}, autofocus: true%>
      <div class="saved-value"></div>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button id="the-one" class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="my-container">
    	<%= render 'layouts/index' %>
    	<%= yield :table %>
    	<%= render 'layouts/before_query' %>
    	<%= render 'layouts/footer' %>

    </div>
</body>
</html>